btlstattracker/core/views.py
# core/views.py

from flask import render_template,request,Blueprint
from flask_security import current_user

core = Blueprint('core',__name__)

@core.route('/')
def index():
    #MORE TO COME!
    return render_template('index.html')
    #return render_template('index.html',current_user=current_user)

@core.route('/info')
def info():
    return render_template('info.html')

btlstattracker/games/views.py
# games/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint,session,jsonify
#from flask_login import login_user,current_user,logout_user,login_required
#from flask_user import current_user, roles_required
from btlstattracker import db
from btlstattracker.models import Games,GamesFromRiot,Players
from btlstattracker.games.forms import MatchInfo,TeamInfo,PlayerInfo
from btlstattracker.games.matchinfofunctions import getMatchInfo,getListOfPlayers, \
    getChampList,getTeamPlayers,convertToString,addInfoToPlayers,updateForSubs
import requests
import json
import pandas as pd
from flask_security import login_required,roles_required,current_user
#from btlstattracker.user.picture_handler import add_profile_pic

#TODO:Add Fill position for subs roles
games = Blueprint('games',__name__)

@games.route('/matchinfo',methods=['POST','GET'])
@login_required
@roles_required('admin')
def matchinfo():

    form = MatchInfo()
    if form.validate_on_submit():

        api = form.api.data
        match_id = form.match_id.data
        match_info = getMatchInfo(api,match_id)
        champ_list,champions_dict = getChampList(match_info)

        session['match_id'] = match_id
        session['season_number'] = form.season_number.data
        session['game_week'] = form.game_week.data
        #session['game_date'] = form.game_date.data
        session['champions_dict'] = champions_dict
        match_info = json.dumps(match_info)

        new_game = GamesFromRiot(match_id=match_id,game=match_info)
        db.session.add(new_game)
        db.session.commit()
        try:
            return redirect(url_for('games.teaminfo'))
        except:
            return redirect(url_for('core.index'))
    return render_template('matchinfo.html',form=form)

@games.route('/teaminfo',methods=['GET','POST'])
@login_required
@roles_required('admin')
def teaminfo():
    try:
        form = TeamInfo()

        teams = list(set([x.team for x in db.session.query(Players).all()]))
        form.blue_team.choices = teams
        form.red_team.choices = teams
        records_df,stats,stats_df = getListOfPlayers()
        session['records_df'] = records_df.to_dict('list')
        session['stats'] = stats
        if form.validate_on_submit():
            blue_team = form.blue_team.data
            red_team = form.red_team.data
            red_team_df,blue_team_df,sub_list,red_list,blue_list=getTeamPlayers(records_df,red_team,blue_team)
            session['red_team_df'] = red_team_df.to_dict()
            session['blue_team_df'] = blue_team_df.to_dict()
            session['red_list'] = red_list
            session['blue_list'] = blue_list
            return redirect(url_for('games.playerinfo'))
    except:
        print('not working')
    return render_template('teaminfo.html',form=form)

@games.route('/playerinfo',methods=['GET','POST'])
@login_required
@roles_required('admin')
def playerinfo():

    match_id = session.get('match_id')
    match_info = db.session.query(GamesFromRiot).filter(GamesFromRiot.match_id == match_id).first().game
    match_info = json.loads(match_info)
    champ_list,champions_dict = getChampList(match_info)
    sub_list = [x.summoner for x in db.session.query(Players).filter(Players.sub_or_player == 'Sub')]
    sub_list.insert(0,' ')
    week_number = session.get('week_number',None)
    season_number = session.get('season_number',None)
    red_team_df_dict = session.get('red_team_df',None)
    blue_team_df_dict = session.get('blue_team_df',None)
    red_team_df = pd.DataFrame.from_dict(red_team_df_dict)
    blue_team_df = pd.DataFrame.from_dict(blue_team_df_dict)
    stats = session.get('stats',None)

    form = PlayerInfo()
    #choices
    positions_dict = {'Blue Top':'blue_top','Blue Jungle':'blue_jungle','Blue Mid':'blue_middle',
                'Blue ADC':'blue_adc','Blue Support':'blue_support','Red Top':'red_top',
                'Red Jungle':'red_jungle','Red Mid':'red_middle','Red ADC':'red_adc',
                'Red Support':'red_support'}
    sub_dict = {'blue_top_sub':None,'blue_jungle_sub':None,'blue_middle_sub':None,
                'blue_adc_sub':None,'blue_support_sub':None,'red_top_sub':None,
                'red_jungle_sub':None,'red_middle_sub':None,'red_adc_sub':None,'red_support_sub':None}

    form.blue_top.choices = champ_list
    form.blue_jungle.choices = champ_list
    form.blue_middle.choices = champ_list
    form.blue_adc.choices = champ_list
    form.blue_support.choices = champ_list
    form.red_top.choices = champ_list
    form.red_jungle.choices = champ_list
    form.red_middle.choices = champ_list
    form.red_adc.choices = champ_list
    form.red_support.choices = champ_list

    form.blue_top_sub.choices = sub_list
    form.blue_jungle_sub.choices = sub_list
    form.blue_middle_sub.choices = sub_list
    form.blue_adc_sub.choices = sub_list
    form.blue_support_sub.choices = sub_list
    form.red_top_sub.choices = sub_list
    form.red_jungle_sub.choices = sub_list
    form.red_middle_sub.choices = sub_list
    form.red_adc_sub.choices = sub_list
    form.red_support_sub.choices = sub_list


    if form.validate_on_submit():

        positions_dict['Blue Top'] = form.blue_top.data
        positions_dict['Blue Jungle'] = form.blue_jungle.data
        positions_dict['Blue Mid'] = form.blue_middle.data
        positions_dict['Blue ADC'] = form.blue_adc.data
        positions_dict['Blue Support'] = form.blue_support.data
        positions_dict['Red Top'] = form.red_top.data
        positions_dict['Red Jungle'] = form.red_jungle.data
        positions_dict['Red Mid'] = form.red_middle.data
        positions_dict['Red ADC'] = form.red_adc.data
        positions_dict['Red Support'] = form.red_support.data

        sub_dict['blue_top_sub'] = form.blue_top_sub.data
        sub_dict['blue_jungle_sub'] = form.blue_jungle_sub.data
        sub_dict['blue_middle_sub'] = form.blue_middle_sub.data
        sub_dict['blue_adc_sub'] = form.blue_adc_sub.data
        sub_dict['blue_support_sub'] = form.blue_support_sub.data
        sub_dict['red_top_sub'] = form.red_top_sub.data
        sub_dict['red_jungle_sub'] = form.red_jungle_sub.data
        sub_dict['red_middle_sub'] = form.red_middle_sub.data
        sub_dict['red_adc_sub'] = form.red_adc_sub.data
        sub_dict['red_support_sub'] = form.red_support_sub.data

        red_team_df,blue_team_df = updateForSubs(sub_dict,red_team_df,blue_team_df)
        player_dict,teams_df = addInfoToPlayers(match_info,week_number,season_number,red_team_df,blue_team_df,stats,positions_dict,champions_dict)

        season_number = session.get('season_number')
        game_week_number = session.get('game_week')

        for index,row in teams_df.iterrows():
            game = Games(season = season_number,
                game_week = game_week_number,
                #game_date = session.get('game_date',None),
                game_id = match_id,
                summoner = row['Summoner'],
                role = row['Role'],
                team = row['Team'],
                sub_or_player = row['Sub or Player'],
                champion_id = row['championId'],
                game_duration = row['gameDuration'],
                ban_1 = row['ban 1'],
                ban_2 = row['ban 2'],
                ban_3 = row['ban 3'],
                ban_4 = row['ban 4'],
                ban_5 = row['ban 5'],
                win = row['win'],
                kills = row['kills'],
                deaths = row['deaths'],
                assists = row['assists'],
                total_damage_dealt = row['totalDamageDealt'],
                vision_score = row['visionScore'],
                gold_earned = row['goldEarned'],
                total_minions_killed = row['totalMinionsKilled'],
                first_blood_kill = row['firstBloodKill'],
                creeps_per_min_deltas_0_10 = row['creepsPerMinDeltas: 0-10'],
                creeps_per_min_deltas_10_20 = row['creepsPerMinDeltas: 10-20'],
                creeps_per_min_deltas_20_30 = row['creepsPerMinDeltas: 20-30'],
                creeps_per_min_deltas_30_end = row['creepsPerMinDeltas: 30-end'],
                gold_per_min_deltas_0_10 = row['goldPerMinDeltas: 0-10'],
                gold_per_min_deltas_10_20 = row['goldPerMinDeltas: 10-20'],
                gold_per_min_deltas_20_30 = row['goldPerMinDeltas: 20-30'],
                gold_per_min_deltas_30_end = row['goldPerMinDeltas: 30-end'])

            db.session.add(game)
            db.session.commit()
            session.clear()

            for key in list(session.keys()):
                 session.pop(key)
        return redirect(url_for('core.index'))
    return render_template('playerinfo.html',form=form)

btlstattracker/players/views.py
#players/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_user import current_user, login_required, roles_required
#TODO: add logout and login?
from btlstattracker import db
from btlstattracker.models import Players
from btlstattracker.players.forms import AddPlayer,SelectPlayer,UpdatePlayer
import sqlite3 as sql
import pandas as pd

players = Blueprint('players',__name__)

@players.route('/allplayers',methods=['GET'])
@login_required
@roles_required('admin')
def allplayers():
    df = pd.read_sql(sql = 'SELECT * FROM Players',con = db.session.bind,index_col =['id'] ,columns = ['Summoner','Role','Team','Sub or Player'])
    return render_template('allplayers.html',data=df.to_html())

#add player
@players.route('/addplayer',methods=['GET','POST'])
@login_required
@roles_required('admin')
def newplayer():
    form = AddPlayer()

    if form.validate_on_submit():
        player = Players(summoner=form.summoner.data,
                        role = form.role.data,
                        team = form.team.data,
                        sub_or_player = form.sub_or_player.data)
        db.session.add(player)
        db.session.commit()
        flash('Player added successfully!')
        return redirect(url_for('players.newplayer'))

    return render_template('addplayer.html',form=form)

#update player
@players.route('/update_or_delete_player',methods=['GET','POST'])
@login_required
@roles_required('admin')
def update_or_delete_player():
    form1 = SelectPlayer()

    if form1.validate_on_submit():

        summoner_choice = form1.summoner.data
        summoner_to_update = Players.query.filter_by(summoner=summoner_choice).first()

        if form1.update_or_delete_player.data == 'update':

            form2 = UpdatePlayer()

            if form2.validate_on_submit():
                summoner_to_update.summoner = form2.summoner.data
                summoner_to_update.role = form2.role.data
                summoner_to_update.team = form2.team.data
                summoner_to_update.sub_or_player = form2.sub_or_player.data
                db.session.commit()
                flash('Player Updated')
                return redirect(url_for('players.update_or_delete_player'))
            return render_template('updateplayer.html',form2=form2)

        elif form1.update_or_delete_player.data == 'delete':

            if form1.validate_on_submit():
                db.session.delete(summoner_to_update)
                db.session.commit()
                flash('Player has been deleted')
                return redirect(url_for('core.index'))
            return render_template('update_or_delete_player.html',form1=form1)
    return render_template('update_or_delete_player.html',form1=form1)

btlstattracker/templates/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endwith %}

btlstattracker/templates/account.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
  <div align='center'>
    <h1>Welcome to the page for {{current_user.username}}</h1>
    <img align='center'src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
  </div>

</div>

<div class="container">
  <form method="POST">

    <div class="form-group">
      {{form.hidden_tag()}}
    </div>

    <div class="form-group">
    {{form.username.label(class='form-group')}}{{form.username(class='form-control')}}
    </div>

    <div class="form-group">
    {{form.email.label(class='form-group')}}{{form.email(class='form-control')}}
    </div>

    <div class="form-group">
    {{form.picture.label(class='form-group')}}{{form.picture(class='form-control')}}
    </div>

    <div class="form-group">
    {{form.submit(class='btn btn-primary')}}
    </div>

  </form>
</div>
{% endblock %}

btlstattracker/templates/addplayer.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{form.hidden_tag()}}
    {{form.summoner.label}}{{form.summoner}}<br>
    {{form.role.label}}{{form.role}}<br>
    {{form.team.label}}{{form.team}}<br>
    {{form.sub_or_player.label}}{{form.sub_or_player}}<br>
    {{form.submit()}}

  </form>
{% endblock %}

btlstattracker/templates/allplayers.html
{% extends "base.html" %}
{% block content %}

    <h1>ALL PLAYERS TABLE</h1>
    {{data | safe}}

  <a href="/">Go back to home page</a>
{% endblock %}

btlstattracker/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">


    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <ul class='navbar'>
      <li class='nav-link'>
        <a href="{{url_for('core.index')}}">Home</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">About</a>
      </li>

      {% if current_user.is_authenticated %}
      <li class='nav-link'>
        <a href="{{url_for_security('logout')}}">Log Out</a>
      </li>
      <!-- <li class='nav-link'>
        <a href="{#{url_for('user.account')}#}">Account</a>
      </li> -->
      <!-- <li class='nav-link'>
        <a href="#">Create Post</a>
      </li> -->
      <li class='nav-link'>
        <a href="{{url_for('players.allplayers')}}">View All Players</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('players.newplayer')}}">Add Player</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('players.update_or_delete_player')}}">Update or Delete Player</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('games.matchinfo')}}">Get Match Info</a>
      </li>
      {% else %}
      <li class='nav-link'>
        <a href="{{url_for_security('login')}}">Login</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for_security('register')}}">Register</a>
      </li>
      {% endif %}
      {% if current_user.has_role('admin') %}
      <li class='nav-link'>
        <a href="/admin">BTL Database</a>
      </li>
      {% endif %}


    </ul>
    <div class="container">
      {% block content %}

      {% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

btlstattracker/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>The Bubble Tea League Official Website!</h1>
</div>
{% endblock %}

btlstattracker/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
  <h1>About The Bubble Tea League</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

btlstattracker/templates/matchinfo.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{form.hidden_tag()}}
    {{form.api.label}}{{form.api}}<br>
    {{form.match_id.label}}{{form.match_id}}<br>
    {{form.season_number.label}}{{form.season_number}}<br>
    {{form.game_week.label}}{{form.game_week}}<br>
    <!-- TODO: -->
    {# form.game_date.label #}{# form.game_date #}<br>
    {{form.submit()}}

  </form>
{% endblock %}

btlstattracker/templates/playerinfo.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{form.hidden_tag()}}
    {{form.blue_top.label}}{{form.blue_top}}<br>
    {{form.blue_top_sub.label}}{{form.blue_top_sub}}<br>
    {{form.blue_jungle.label}}{{form.blue_jungle}}<br>
    {{form.blue_jungle_sub.label}}{{form.blue_jungle_sub}}<br>
    {{form.blue_middle.label}}{{form.blue_middle}}<br>
    {{form.blue_middle_sub.label}}{{form.blue_middle_sub}}<br>
    {{form.blue_adc.label}}{{form.blue_adc}}<br>
    {{form.blue_adc_sub.label}}{{form.blue_adc_sub}}<br>
    {{form.blue_support.label}}{{form.blue_support}}<br>
    {{form.blue_support_sub.label}}{{form.blue_support_sub}}<br>
    {{form.red_top.label}}{{form.red_top}}<br>
    {{form.red_top_sub.label}}{{form.red_top_sub}}<br>
    {{form.red_jungle.label}}{{form.red_jungle}}<br>
    {{form.red_jungle_sub.label}}{{form.red_jungle_sub}}<br>
    {{form.red_middle.label}}{{form.red_middle}}<br>
    {{form.red_middle_sub.label}}{{form.red_middle_sub}}<br>
    {{form.red_adc.label}}{{form.red_adc}}<br>
    {{form.red_adc_sub.label}}{{form.red_adc_sub}}<br>
    {{form.red_support.label}}{{form.red_support}}<br>
    {{form.red_support_sub.label}}{{form.red_support_sub}}<br>
    {{form.submit()}}
  </form>
{% endblock %}

btlstattracker/templates/teaminfo.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{form.hidden_tag()}}
    {{form.blue_team.label}}{{form.blue_team}}<br>
    {{form.red_team.label}}{{form.red_team}}<br>
    {{form.submit()}}

  </form>
{% endblock %}

btlstattracker/templates/update_or_delete_player.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{form1.hidden_tag()}}
    {{form1.summoner.label}}{{form1.summoner}}<br>
    {{form1.update_or_delete_player.label}}{{form1.update_or_delete_player}}<br>
    {{form1.submit()}}

  </form>
{% endblock %}

btlstattracker/templates/updateplayer.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
      {{form2.hidden_tag()}}
      {{form2.summoner.label}}{{form2.summoner}}<br>
      {{form2.role.label}}{{form2.role}}<br>
      {{form2.team.label}}{{form2.team}}<br>
      {{form2.sub_or_player.label}}{{form2.sub_or_player}}<br>
      {{form2.submit()}}
  </form>
{% endblock %}

btlstattracker/templates/user_game.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="container">
    <div align='center'>
      <h1>Welcome to the page for {{user.username}}</h1>
      <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
    </div>
  </div>


{% for game in games.items %}
    <h2> <a href="{{url_for('games.game',game_id=game.id)}}">{{game.title}}</a> </h2>
    Game Title: <a href="{{url_for('user.user_game',username==game.author.username)}}">{{game.author.username}}</a>
    <p class='text-muted'>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
    <br>
    <p>{{game.text}}</p>
    <br>
{% endfor %}
</div>

<nav aria-label='Page Navigation example'>
  <ul class='pagination justify-content-center'>
    {% for page_num in games.iter_pages(lef_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if games.page == page_num %}
            <li class='page-item disabled'>
              <a class='page-link' href="{{url_for('user.user_games',username=user.username,page=page_num)}}">{{page_num}}</a>
            </li>
        {% else %}
            <li class='page-item'>
              <a class='page-link' href="{{url_for('user.user_games',username=user.username,page=page_num)}}">{{page_num}}</a>
            </li>
        {% endif %}
    {% endfor %}
  </ul>

</nav>

{% endblock %}